language: c++

branches:
  except:
    - automatic

cache:
  directories:
    - download

matrix:
  include:
    os: linux
    dist: xenial
    env:
      - _BUILD=linux64
    before_install:
      - sudo apt-get update -qq
    install:
      - sudo apt-get install build-essential pkg-config libasound2-dev libpulse-dev libglu1-mesa-dev libjack-jackd2-dev libsndfile1-dev libsoxr-dev mesa-common-dev libqt5opengl5-dev libqt5x11extras5-dev qtbase5-dev qttools5-dev qttools5-dev-tools qt5-default liblo-dev checkinstall
    script:
      - mkdir release
      - mkdir build
      - cd build
      - cmake -DCMAKE_BUILD_TYPE=Release ..
      - cmake --build .
      - echo "An Interactive Granular Sampler" > description-pak
      - |
        if test "$TRAVIS_BRANCH" = "develop" -a "$TRAVIS_PULL_REQUEST" = "false"; then
          sudo checkinstall --type=debian --install=no --default --pkgname=frontieres --pkgversion="`git describe --abbrev=0 | sed 's/^v//'``git log -n 1 --pretty=format:"+%cd~git%h" --date=short develop | sed 's/-//g'`" --pkgarch=amd64 --pkgrelease=0linuxmao1 --pkglicense=GPL-3.0-only --pkggroup=sound --maintainer="jp-dev@inbox.ru" --nodoc
          sudo mv -f *.deb ../release/frontieres-"$_BUILD".deb
        fi
      - cd ..

before_deploy:
  - |
    if test "$TRAVIS_BRANCH" = "develop" -a "$TRAVIS_PULL_REQUEST" = "false"; then
      export TRAVIS_TAG=automatic
      git tag -f "$TRAVIS_TAG"
    fi

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: release/*
  file_glob: true
  prerelease: true
  overwrite: true
  edge: true
  on:
    branch: develop

env:
  global:
    secure: "RCSXvmWoixICBpQBv0ew5BsT+wjHooCMaoYwqQqpBHsCo+ZPw97CFYepBYHrnhXxWm2sXdGPmc01qv/GAY4JfDMISMy9orVdgtOcWJwSLX+aM5cRYodtzapsyP97l+Rb68NPU8bQkhA3OS6FWRbZwed+JDwH2oD13LnDIhRpS2PBvDks0kN7dnf/J0YaLCLcY9WttBvCym3PwDZet9txHn8ill/1yGO9oERfUW3ZQVES5/qGva2iCX3vHRlc4MPEyqpBPMlPl8e4Xnr1OZKh3p76ApvJLAXKWzAtudcUULjZDDkEs9ZYOBD39cR7UNvPtQBa/U6QfZ6nStUvqhkps54zzj1qn5v+VMLTT9YhSjO0F+ohPYixyZn+lrkoL9kVZzo/ySAhpW8OK+SmfndMXizkDpQ7tYWUfdf9aQ6cAzwaUgnpLiMqICUkLTAhtbNutixj7a+IQyKTWhoGRlXdK7ZhFBK3Mk2CBBPwvn3l9h7ytf2HaRpn1jsUQhBsa/s71t/7xagoEX/EWI1WwzGGRWmHtpWyU1ZlwafUISzV8kOQIFuYN3kZy/VL5f6Hmsg6q9m50M+eIZ8X0LQ6M/GJQwb9l9qUO+Xr0G0jRTGdi9ospdydsQVbt98Ai8Z4Y8830QY8UA0txK3YeR55lJeQH0QE8Ef+qxFGBoc8GjqOljg="

notifications:
  irc:
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    channels:
      - "ircs://chat.freenode.net:7070/#librazik"
